apiVersion: apps/v1
kind: Deployment
metadata:
  name: zendrix
  labels:
    app: zendrix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zendrix
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: zendrix
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: zendrix
        image: mpawar006/zendrix-project1:latest
        imagePullPolicy: Always               # pull :latest every time
        ports:
        - containerPort: 85
        readinessProbe:
          httpGet:
            path: /
            port: 85
          initialDelaySeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 85
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "128Mi"
