apiVersion: apps/v1
kind: Deployment
metadata:
  name: zendrix
  labels:
    app: zendrix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zendrix
  template:
    metadata:
      labels:
        app: zendrix
    spec:
      # If the Docker Hub repo is private, create an imagePullSecret
      # and uncomment the next three lines.
      # imagePullSecrets:
      # - name: regcred
      containers:
      - name: zendrix
        image: mpawar006/zendrix-project1:latest        # tag gets updated by Job 2
        ports:
        - containerPort: 85
