apiVersion: apps/v1
kind: Deployment
metadata:
  name: zendrix
  labels:
    app: zendrix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zendrix
  template:
    metadata:
      labels:
        app: zendrix
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: zendrix
        image: mpawar006/zendrix-project1:latest  # This gets updated by Job 2
        ports:
        - containerPort: 85
