apiVersion: v1
kind: Service
metadata:
  name: zendrix-svc
spec:
  selector:
    app: zendrix
  type: NodePort         # Use LoadBalancer if you’re on a managed cloud
  ports:
  - port: 85
    targetPort: 85
    nodePort: 30085      # Fixed NodePort; omit for dynamic assignment
